apiVersion: v1
kind: Service
metadata:
  name: stg-track-my-case-service
spec:
  selector:
    app: stg-track-my-case-dpc-stub-api-dev # this should match the pod label in deployment.yml
  ports:
    - name: https
      port: 8080
      targetPort: 8080
